[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000024C9CD100D0>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000024C9CCA1150>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000024C9CD2C710>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000024C9CCB6B50>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000024C9CD9A110>, 'Connection to 127.0.0.1 timed out. (connect timeout=1.0)')': /status